version: 2
jobs:
  build_test_deploy:
    machine: true
    steps:
      - checkout

      - run:
          name: Install tools
          command: |
            sudo apt-get update
            sudo apt-get install jq -y

      - run:
          name: Build docker image
          command: docker build -t "scalableminds/webknossos-cuber:${CIRCLE_BUILD_NUM}" .

      - run:
          name: Test tiff cubing
          command: |
            set -x
            mkdir -p testoutput/tiff
            docker run \
              -v "${PWD}/testdata:/testdata" \
              -v "${PWD}/testoutput:/testoutput" \
              --rm \
              scalableminds/webknossos-cuber:${CIRCLE_BUILD_NUM} \
              wkcuber.cubing \
              --verbose \
              --layer_name color \
              /testdata/tiff /testoutput/tiff
            [ -d testoutput/tiff/color ]
            [ -d testoutput/tiff/color/1 ]
            [ $(find testoutput/tiff/color/1 -mindepth 3 -name "*.wkw" | wc -l) -eq 1 ]

      - run:
          name: Test KNOSSOS conversion
          command: |
            set -x
            mkdir -p testoutput/knossos
            docker run \
              -v "${PWD}/testdata:/testdata" \
              -v "${PWD}/testoutput:/testoutput" \
              --rm \
              scalableminds/webknossos-cuber:${CIRCLE_BUILD_NUM} \
              wkcuber.convert \
              --verbose \
              --dtype uint8 \
              --layer_name color \
              --mag 1 \
              /testdata/knossos /testoutput/knossos
            [ -d testoutput/knossos/color ]
            [ -d testoutput/knossos/color/1 ]
            [ $(find testoutput/knossos/color/1 -mindepth 3 -name "*.wkw" | wc -l) -eq 1 ]

      - run:
          name: Test downsampling
          command: |
            set -x
            docker run \
              -v "${PWD}/testoutput:/testoutput" \
              --rm \
              scalableminds/webknossos-cuber:${CIRCLE_BUILD_NUM} \
              wkcuber.downsampling \
              --verbose \
              --max 8 \
              --layer_name color \
              /testoutput/tiff
            [ -d testoutput/tiff/color/2 ]
            [ -d testoutput/tiff/color/4 ]
            [ -d testoutput/tiff/color/8 ]
            [ -n testoutput/tiff/color/16 ]
            [ $(find testoutput/knossos/color/2 -mindepth 3 -name "*.wkw" | wc -l) -eq 1 ]
            [ $(find testoutput/knossos/color/4 -mindepth 3 -name "*.wkw" | wc -l) -eq 1 ]
            [ $(find testoutput/knossos/color/8 -mindepth 3 -name "*.wkw" | wc -l) -eq 1 ]

      - run:
          name: Test compression
          command: |
            set -x
            docker run \
              -v "${PWD}/testoutput:/testoutput" \
              --rm \
              scalableminds/webknossos-cuber:${CIRCLE_BUILD_NUM} \
              wkcuber.compress \
              --verbose \
              --layer_name color \
              /testoutput/tiff /testoutput/tiff_compress
            [ -d testoutput/tiff_compress/color/1 ]
            [ -d testoutput/tiff_compress/color/2 ]
            [ -d testoutput/tiff_compress/color/4 ]
            [ -d testoutput/tiff_compress/color/8 ]

      - run:
          name: Test in-place compression
          command: |
            set -x
            cp -r testoutput/tiff testoutput/tiff_compress2
            docker run \
              -v "${PWD}/testoutput:/testoutput" \
              --rm \
              scalableminds/webknossos-cuber:${CIRCLE_BUILD_NUM} \
              wkcuber.compress \
              --verbose \
              --layer_name color \
              /testoutput/tiff_compress2

      - run:
          name: Test metadata generation
          command: |
            set -x
            docker run \
              -v "${PWD}/testoutput:/testoutput" \
              --rm \
              scalableminds/webknossos-cuber:${CIRCLE_BUILD_NUM} \
              wkcuber.metadata \
              --name test_dataset \
              --scale 11.24,11.24,25 \
              /testoutput/tiff
            [ -e testoutput/tiff/datasource-properties.json ]
            jq --argfile a testdata/tiff/datasource-properties.fixture.json --argfile b testoutput/tiff/datasource-properties.json -n '$a == $b'
            # diff testdata/tiff/datasource-properties.fixture.json testoutput/tiff/datasource-properties.json

      - run:
          name: Push docker images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push scalableminds/webknossos-cuber:$CIRCLE_BUILD_NUM
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag scalableminds/webknossos-cuber:$CIRCLE_BUILD_NUM scalableminds/webknossos-cuber:latest
              docker push scalableminds/webknossos-cuber:latest
            fi
            docker logout

workflows:
  version: 2
  default:
    jobs:
      - build_test_deploy
