name: Auto Assign Issues to Project

on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_issue_to_project:
    runs-on: ubuntu-latest
    steps:
    - uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/orgs/scalableminds/projects/6'
        column_name: Backlog
